### ISSUE TITLE
Error: Cannot find module 'algoliasearch'

### ISSUE THREAD

**Issue by morariu** [MunifTanjim/minimo#302]
Running the following command after installing **algoliasearch** and **glob** globally:

`node ./themes/minimo/scripts/generate-search-index-algolia.js`

Getting this error:

```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'algoliasearch'
Require stack:
- /home/laur/hugo/pijat/themes/minimo/scripts/generate-search-index-algolia.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/laur/hugo/pijat/themes/minimo/scripts/generate-search-index-algolia.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/laur/hugo/pijat/themes/minimo/scripts/generate-search-index-algolia.js'
  ]
}

```

**Comment by MunifTanjim** [comment]
How did you setup Node.js on your system? This error is happening because your Node.js installation couldn't resolve the globally installed `algoliasearch` package.

**Comment by morariu** [comment]
Thanks. Well, Node.js is installed globally. The Node version is v12.16.1 and the npm version is 6.14.4.
